export const CREATE_USER = 'CREATE_USER';
export const GET_USERS = 'GET_USERS';
export const CREATE_USER_SUCCESSFUL = 'CREATE_USER_SUCCESSFUL';
export const FETCH_USERS_SUCCESSFUL = 'FETCH_USERS_SUCCESSFUL';
export const UPDATE_USER = "UPDATE_USER"
export const UPDATE_USER_SUCCESSFUL = "UPDATE_USER_SUCCESSFUL"

export const USER_API_ERROR = 'USER_API_ERROR';