export const CREATE_REQUISITION = 'CREATE_REQUISITION';
export const GET_REQUISITION = 'GET_REQUISITION';
export const CREATE_REQUISITION_SUCCESSFUL = 'CREATE_REQUISITION_SUCCESSFUL';
export const FETCH_REQUISITION_SUCCESSFUL = 'FETCH_REQUISITION_SUCCESSFUL';
// Request Detail field
export const FETCH_REQUISITION_DETAILS = 'FETCH_REQUISITION_DETAILS';
export const FETCH_REQUISITION_DETAILS_SUCCESSFUL =
  'FETCH_REQUISITION_DETAILS_SUCCESSFUL';
  // Update Field
export const UPDATE_REQUISITION = 'UPDATE_REQUISITION';
export const UPDATE_REQUISITION_SUCCESSFUL = 'UPDATE_REQUISITION_SUCCESSFUL';

export const API_ERROR = 'api_failed';
