export const CREATE_VENDOR = 'CREATE_VENDOR';
export const GET_VENDORS = 'GET_VENDORS';
export const CREATE_VENDOR_SUCCESSFUL = 'CREATE_VENDOR_SUCCESSFUL';
export const FETCH_VENDORS_SUCCESSFUL = 'FETCH_VENDORS_SUCCESSFUL';
export const UPDATE_VENDOR = "UPDATE_VENDOR"
export const UPDATE_VENDOR_SUCCESSFUL = "UPDATE_VENDOR_SUCCESSFUL"

export const VENDOR_API_ERROR = 'VENDOR_API_ERROR';
